### ISSUE TITLE
Hi Vishnu

### ISSUE THREAD

**Issue by DominicSamoes** [VishnuSivadasVS/LogIn-SignUp#2]
Appreciate your work. The signup button to Login in the Android app seems not to work. Data is uploaded to the database but no movement to the Login activity.

**Comment by VishnuSivadasVS** [comment]
I think you are talking about the video on YouTube, if the signup is not dine successfully then the login page wont automatically open. You might have made some minute careless mistake. Watch the video once more carefully and you will be able to fix it.

**Comment by DominicSamoes** [comment]
You were right the mistake was minute. Fixed it.

**Comment by DominicSamoes** [comment]
Instead of **result.equals("Sign Up Success")** I had typed **result.equals("Signup Success")** which was different from the signup.php script.
